print(1, "True and True :", True and True)
print(2, "False and True :", False and True)
print(3, "1 == 1 and 2 == 1 :", 1 == 1 and 2 == 1)
print(4, '"test" == "test" :', "test" == "test")
print(5, "1 == 1 or 2 != 1 :", 1 == 1 or 2 != 1)
print(6, "True and 1 == 1 :", True and 1 == 1)
print(7, "False and 0 != 0 :", False and 0 != 0)
print(8, "True or 1 == 1 :", True or 1 == 1)
print(9, '"test" == "testing" :', "test" == "testing")
print(10, "1 != 0 and 2 == 1 :", 1 != 0 and 2 == 1)
print(11, '"test" != "testing" :', "test" != "testing")
print(12, '"test" == 1 :', "test" == 1)
print(13, "not(True and False) :", not(True and False))
print(14, "not(1 == 1 and 0 != 1) :", not(1 == 1 and 0 != 1))
print(18, "not(10 == 1 or 1000 == 1000) :", not(10 == 1 or 1000 == 1000))
print(19, "not(1 != 0 or 3 == 4) :", not(1 != 0 or 3 == 4))
print(20, 'not("testing" == "testing" and "Zed" == "Cool Guy") :', not("testing" == "testing" and "Zed" == "Cool Guy"))
print(21, '1 == 1 and (not("testing" == 1 or 1 == 0)) :',1 == 1 and (not("testing" == 1 or 1 == 0)))
print(22, '"chunky" == "bacon" and (not(3 == 4 or 3 == 3)) :', "chunky" == "bacon" and (not(3 == 4 or 3 == 3)))
print(23, '3 == 3 and (not("testing" == "testing" or "Python" == "Fun")) :', 3 == 3 and (not("testing" == "testing" or "Python" == "Fun")))
